### ISSUE TITLE
.NET Core support missing

### ISSUE THREAD

**Issue by sandromastronardi** [kroimon/ExpirableItemDictionary#1]
Hi, the library isn't supporting .NET Core yet (or .NET Standard)... with .NET moving to .NET 5 this might be very useful...

**Comment by kroimon** [comment]
Pull requests for this would be very welcome!

**Comment by sandromastronardi** [comment]
I would have done that if it wasn't very intrusive... the csproj setup is quite different, so needs to be replaced and then I don't know what you still need from it... it's not so difficult, just a big change to do on my own on someone else's project ;-)

**Comment by sandromastronardi** [comment]
Which DotnetFramework versions is it currently supporting? can't see that in the project file...

**Comment by kroimon** [comment]
The library is currently targeting .NET Framework 3.5 as a common minimum as can be seen in ExpirableItemDictionary.csproj (search for TargetFrameworkVersion).

**Comment by kroimon** [comment]
Hints on how to create multi-platform nuget packages can be found [here at Microsoft Docs](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks) and probably [here](https://medium.com/@vasugupta/c-in-5-mins-creating-nuget-packages-which-target-multiple-frameworks-4c2e1ee26614) and/or [here](https://www.michalbialecki.com/2020/08/21/how-to-create-a-nuget-package-targeting-multiple-frameworks/).

I never did that myself and currently lack the time of implementing this, so I would greatly appreciate pull requests.

**Comment by sandromastronardi** [comment]
hmm, ok, i missed the targeting somehow...
Ok, so .NET 3.5, .NET Standard 2.0, .NET Core 2.1 and .NET Core 3.1 are ok for you?

**Comment by sandromastronardi** [comment]
PR Ready

**Comment by kroimon** [comment]
Solved in #2.
Thanks again for your help!
